// Code generated by protoc-gen-go. DO NOT EDIT.
// source: supervisor.proto

package supervisor

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Node_NodeType int32

const (
	Node_Leader Node_NodeType = 0
	Node_Member Node_NodeType = 1
)

var Node_NodeType_name = map[int32]string{
	0: "Leader",
	1: "Member",
}

var Node_NodeType_value = map[string]int32{
	"Leader": 0,
	"Member": 1,
}

func (x Node_NodeType) String() string {
	return proto.EnumName(Node_NodeType_name, int32(x))
}

func (Node_NodeType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_b8b9452d77b1c7d2, []int{0, 0}
}

type Node struct {
	Type                 Node_NodeType `protobuf:"varint,1,opt,name=type,proto3,enum=supervisor.Node_NodeType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Node) Reset()         { *m = Node{} }
func (m *Node) String() string { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()    {}
func (*Node) Descriptor() ([]byte, []int) {
	return fileDescriptor_b8b9452d77b1c7d2, []int{0}
}

func (m *Node) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Node.Unmarshal(m, b)
}
func (m *Node) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Node.Marshal(b, m, deterministic)
}
func (m *Node) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Node.Merge(m, src)
}
func (m *Node) XXX_Size() int {
	return xxx_messageInfo_Node.Size(m)
}
func (m *Node) XXX_DiscardUnknown() {
	xxx_messageInfo_Node.DiscardUnknown(m)
}

var xxx_messageInfo_Node proto.InternalMessageInfo

func (m *Node) GetType() Node_NodeType {
	if m != nil {
		return m.Type
	}
	return Node_Leader
}

type RegisterNodeRequest struct {
	Node                 *Node    `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterNodeRequest) Reset()         { *m = RegisterNodeRequest{} }
func (m *RegisterNodeRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterNodeRequest) ProtoMessage()    {}
func (*RegisterNodeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b8b9452d77b1c7d2, []int{1}
}

func (m *RegisterNodeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterNodeRequest.Unmarshal(m, b)
}
func (m *RegisterNodeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterNodeRequest.Marshal(b, m, deterministic)
}
func (m *RegisterNodeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterNodeRequest.Merge(m, src)
}
func (m *RegisterNodeRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterNodeRequest.Size(m)
}
func (m *RegisterNodeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterNodeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterNodeRequest proto.InternalMessageInfo

func (m *RegisterNodeRequest) GetNode() *Node {
	if m != nil {
		return m.Node
	}
	return nil
}

type RegisterNodeResponse struct {
	// id of added Node
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterNodeResponse) Reset()         { *m = RegisterNodeResponse{} }
func (m *RegisterNodeResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterNodeResponse) ProtoMessage()    {}
func (*RegisterNodeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b8b9452d77b1c7d2, []int{2}
}

func (m *RegisterNodeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterNodeResponse.Unmarshal(m, b)
}
func (m *RegisterNodeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterNodeResponse.Marshal(b, m, deterministic)
}
func (m *RegisterNodeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterNodeResponse.Merge(m, src)
}
func (m *RegisterNodeResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterNodeResponse.Size(m)
}
func (m *RegisterNodeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterNodeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterNodeResponse proto.InternalMessageInfo

func (m *RegisterNodeResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type NodeStatusRequest struct {
	// Node id
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NodeStatusRequest) Reset()         { *m = NodeStatusRequest{} }
func (m *NodeStatusRequest) String() string { return proto.CompactTextString(m) }
func (*NodeStatusRequest) ProtoMessage()    {}
func (*NodeStatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b8b9452d77b1c7d2, []int{3}
}

func (m *NodeStatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeStatusRequest.Unmarshal(m, b)
}
func (m *NodeStatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeStatusRequest.Marshal(b, m, deterministic)
}
func (m *NodeStatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeStatusRequest.Merge(m, src)
}
func (m *NodeStatusRequest) XXX_Size() int {
	return xxx_messageInfo_NodeStatusRequest.Size(m)
}
func (m *NodeStatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeStatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NodeStatusRequest proto.InternalMessageInfo

func (m *NodeStatusRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type NodeStatusResponse struct {
	Result               bool     `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NodeStatusResponse) Reset()         { *m = NodeStatusResponse{} }
func (m *NodeStatusResponse) String() string { return proto.CompactTextString(m) }
func (*NodeStatusResponse) ProtoMessage()    {}
func (*NodeStatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b8b9452d77b1c7d2, []int{4}
}

func (m *NodeStatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeStatusResponse.Unmarshal(m, b)
}
func (m *NodeStatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeStatusResponse.Marshal(b, m, deterministic)
}
func (m *NodeStatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeStatusResponse.Merge(m, src)
}
func (m *NodeStatusResponse) XXX_Size() int {
	return xxx_messageInfo_NodeStatusResponse.Size(m)
}
func (m *NodeStatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeStatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NodeStatusResponse proto.InternalMessageInfo

func (m *NodeStatusResponse) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

func init() {
	proto.RegisterEnum("supervisor.Node_NodeType", Node_NodeType_name, Node_NodeType_value)
	proto.RegisterType((*Node)(nil), "supervisor.Node")
	proto.RegisterType((*RegisterNodeRequest)(nil), "supervisor.RegisterNodeRequest")
	proto.RegisterType((*RegisterNodeResponse)(nil), "supervisor.RegisterNodeResponse")
	proto.RegisterType((*NodeStatusRequest)(nil), "supervisor.NodeStatusRequest")
	proto.RegisterType((*NodeStatusResponse)(nil), "supervisor.NodeStatusResponse")
}

func init() { proto.RegisterFile("supervisor.proto", fileDescriptor_b8b9452d77b1c7d2) }

var fileDescriptor_b8b9452d77b1c7d2 = []byte{
	// 265 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0x41, 0x4b, 0xfb, 0x40,
	0x10, 0xc5, 0xff, 0xe9, 0x3f, 0x86, 0xf8, 0x84, 0x12, 0x47, 0x11, 0x2d, 0xa8, 0x65, 0x15, 0xf1,
	0xa0, 0x3d, 0xc4, 0xa3, 0x77, 0x4f, 0xd6, 0xc3, 0x56, 0x10, 0x8f, 0xa9, 0x3b, 0x68, 0x40, 0xbb,
	0xeb, 0xee, 0x46, 0xe8, 0xd7, 0xf1, 0x93, 0x4a, 0xb6, 0x09, 0xa6, 0xc1, 0x5e, 0x96, 0xdd, 0x79,
	0xbf, 0x99, 0x37, 0x8f, 0x45, 0xe6, 0x2a, 0xc3, 0xf6, 0xab, 0x74, 0xda, 0x4e, 0x8c, 0xd5, 0x5e,
	0x13, 0x7e, 0x2b, 0xe2, 0x19, 0xf1, 0x83, 0x56, 0x4c, 0xd7, 0x88, 0xfd, 0xd2, 0xf0, 0x61, 0x34,
	0x8e, 0x2e, 0x87, 0xf9, 0xd1, 0xa4, 0xd3, 0x54, 0xeb, 0xe1, 0x78, 0x5c, 0x1a, 0x96, 0x01, 0x13,
	0x02, 0x69, 0x5b, 0x21, 0x20, 0xb9, 0xe7, 0x42, 0xb1, 0xcd, 0xfe, 0xd5, 0xf7, 0x29, 0x7f, 0xcc,
	0xd9, 0x66, 0x91, 0xb8, 0xc5, 0x9e, 0xe4, 0xd7, 0xd2, 0x79, 0xb6, 0x35, 0x2b, 0xf9, 0xb3, 0x62,
	0xe7, 0xe9, 0x1c, 0xf1, 0x42, 0xab, 0x95, 0xd3, 0x4e, 0x9e, 0xf5, 0x9d, 0x64, 0x50, 0xc5, 0x05,
	0xf6, 0xd7, 0x9b, 0x9d, 0xd1, 0x0b, 0xc7, 0x34, 0xc4, 0xa0, 0x54, 0xa1, 0xf7, 0xbf, 0x1c, 0x94,
	0x4a, 0x9c, 0x61, 0xb7, 0xd6, 0x67, 0xbe, 0xf0, 0x95, 0x6b, 0x2d, 0xfa, 0xd0, 0x15, 0xa8, 0x0b,
	0x35, 0xa3, 0x0e, 0x90, 0x58, 0x76, 0xd5, 0xbb, 0x0f, 0x64, 0x2a, 0x9b, 0x57, 0xfe, 0x1d, 0x61,
	0x7b, 0xd6, 0x2c, 0xc5, 0x34, 0x45, 0xda, 0x2e, 0x42, 0xa7, 0xdd, 0x65, 0xff, 0xc8, 0x36, 0x1a,
	0x6f, 0x06, 0x1a, 0xd3, 0x3b, 0x6c, 0x3d, 0x15, 0xfe, 0xe5, 0x8d, 0x8e, 0xfb, 0xc1, 0xd7, 0x22,
	0x8c, 0x4e, 0x36, 0xc9, 0xab, 0x39, 0xf3, 0x24, 0x7c, 0xe5, 0xcd, 0x4f, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x3e, 0x8a, 0x6f, 0xfb, 0xde, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SuperviseClient is the client API for Supervise service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SuperviseClient interface {
	Register(ctx context.Context, in *RegisterNodeRequest, opts ...grpc.CallOption) (*RegisterNodeResponse, error)
	Watch(ctx context.Context, in *NodeStatusRequest, opts ...grpc.CallOption) (*NodeStatusResponse, error)
}

type superviseClient struct {
	cc *grpc.ClientConn
}

func NewSuperviseClient(cc *grpc.ClientConn) SuperviseClient {
	return &superviseClient{cc}
}

func (c *superviseClient) Register(ctx context.Context, in *RegisterNodeRequest, opts ...grpc.CallOption) (*RegisterNodeResponse, error) {
	out := new(RegisterNodeResponse)
	err := c.cc.Invoke(ctx, "/supervisor.Supervise/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *superviseClient) Watch(ctx context.Context, in *NodeStatusRequest, opts ...grpc.CallOption) (*NodeStatusResponse, error) {
	out := new(NodeStatusResponse)
	err := c.cc.Invoke(ctx, "/supervisor.Supervise/Watch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SuperviseServer is the server API for Supervise service.
type SuperviseServer interface {
	Register(context.Context, *RegisterNodeRequest) (*RegisterNodeResponse, error)
	Watch(context.Context, *NodeStatusRequest) (*NodeStatusResponse, error)
}

// UnimplementedSuperviseServer can be embedded to have forward compatible implementations.
type UnimplementedSuperviseServer struct {
}

func (*UnimplementedSuperviseServer) Register(ctx context.Context, req *RegisterNodeRequest) (*RegisterNodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (*UnimplementedSuperviseServer) Watch(ctx context.Context, req *NodeStatusRequest) (*NodeStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Watch not implemented")
}

func RegisterSuperviseServer(s *grpc.Server, srv SuperviseServer) {
	s.RegisterService(&_Supervise_serviceDesc, srv)
}

func _Supervise_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SuperviseServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/supervisor.Supervise/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SuperviseServer).Register(ctx, req.(*RegisterNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Supervise_Watch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SuperviseServer).Watch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/supervisor.Supervise/Watch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SuperviseServer).Watch(ctx, req.(*NodeStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Supervise_serviceDesc = grpc.ServiceDesc{
	ServiceName: "supervisor.Supervise",
	HandlerType: (*SuperviseServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _Supervise_Register_Handler,
		},
		{
			MethodName: "Watch",
			Handler:    _Supervise_Watch_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "supervisor.proto",
}
